import { Inter } from "next/font/google";
import "./globals.css";

import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });

const mona = localFont({
  src: './fonts/Mona Sans/Mona-Sans.woff2',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Bg from "./components/global/bg/bg";
import Header from "./components/header/header";

import Smooth from './components/global/smoothScroll/Smooth'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mona.className}>
        <Smooth />
        <Header />
        <Bg />
        {children}</body>
    </html>
  );
}
